# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_cspice_swig')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_cspice_swig')
    _cspice_swig = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cspice_swig', [dirname(__file__)])
        except ImportError:
            import _cspice_swig
            return _cspice_swig
        try:
            _mod = imp.load_module('_cspice_swig', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _cspice_swig = swig_import_helper()
    del swig_import_helper
else:
    import _cspice_swig
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def axisar(axis, angle):
    """axisar(double [3] axis, double angle)"""
    return _cspice_swig.axisar(axis, angle)

def b1900():
    """b1900() -> double"""
    return _cspice_swig.b1900()

def b1950():
    """b1950() -> double"""
    return _cspice_swig.b1950()

def bodc2n(code):
    """bodc2n(int code)"""
    return _cspice_swig.bodc2n(code)

def bodc2s(code):
    """bodc2s(int code)"""
    return _cspice_swig.bodc2s(code)

def boddef(CONST_STRING, code):
    """boddef(char * CONST_STRING, int code)"""
    return _cspice_swig.boddef(CONST_STRING, code)

def bodfnd(body, CONST_STRING):
    """bodfnd(int body, char * CONST_STRING) -> int"""
    return _cspice_swig.bodfnd(body, CONST_STRING)

def bodn2c(CONST_STRING):
    """bodn2c(char * CONST_STRING)"""
    return _cspice_swig.bodn2c(CONST_STRING)

def bods2c(CONST_STRING):
    """bods2c(char * CONST_STRING)"""
    return _cspice_swig.bods2c(CONST_STRING)

def bodvcd(bodyid, CONST_STRING):
    """bodvcd(int bodyid, char * CONST_STRING)"""
    return _cspice_swig.bodvcd(bodyid, CONST_STRING)

def bodvrd(arg1, arg2):
    """bodvrd(char * arg1, char * arg2)"""
    return _cspice_swig.bodvrd(arg1, arg2)

def cgv2el(center, vec1, vec2):
    """cgv2el(double [3] center, double [3] vec1, double [3] vec2)"""
    return _cspice_swig.cgv2el(center, vec1, vec2)

def cidfrm(cent):
    """cidfrm(int cent)"""
    return _cspice_swig.cidfrm(cent)

def ckcov(ck, idcode, needav, level, tol, timsys):
    """ckcov(char * ck, int idcode, int needav, char * level, double tol, char * timsys)"""
    return _cspice_swig.ckcov(ck, idcode, needav, level, tol, timsys)

def ckgp(inst, sclkdp, tol, CONST_STRING):
    """ckgp(int inst, double sclkdp, double tol, char * CONST_STRING)"""
    return _cspice_swig.ckgp(inst, sclkdp, tol, CONST_STRING)

def ckgpav(inst, sclkdp, tol, CONST_STRING):
    """ckgpav(int inst, double sclkdp, double tol, char * CONST_STRING)"""
    return _cspice_swig.ckgpav(inst, sclkdp, tol, CONST_STRING)

def ckobj(ck):
    """ckobj(char * ck)"""
    return _cspice_swig.ckobj(ck)

def clight():
    """clight() -> double"""
    return _cspice_swig.clight()

def clpool():
    """clpool()"""
    return _cspice_swig.clpool()

def cnmfrm(cname):
    """cnmfrm(char * cname)"""
    return _cspice_swig.cnmfrm(cname)

def conics(elts, et):
    """conics(double [8] elts, double et)"""
    return _cspice_swig.conics(elts, et)

def convrt(x, arg2, arg3):
    """convrt(double x, char * arg2, char * arg3)"""
    return _cspice_swig.convrt(x, arg2, arg3)

def cyllat(r, lonc, z):
    """cyllat(double r, double lonc, double z)"""
    return _cspice_swig.cyllat(r, lonc, z)

def cylrec(r, lon, z):
    """cylrec(double r, double lon, double z)"""
    return _cspice_swig.cylrec(r, lon, z)

def cylsph(r, lonc, z):
    """cylsph(double r, double lonc, double z)"""
    return _cspice_swig.cylsph(r, lonc, z)

def dafbfs(handle):
    """dafbfs(int handle)"""
    return _cspice_swig.dafbfs(handle)

def dafcls(handle):
    """dafcls(int handle)"""
    return _cspice_swig.dafcls(handle)

def dafgda(handle, begin, end):
    """dafgda(int handle, int begin, int end)"""
    return _cspice_swig.dafgda(handle, begin, end)

def dafgn():
    """dafgn()"""
    return _cspice_swig.dafgn()

def dafgs():
    """dafgs()"""
    return _cspice_swig.dafgs()

def daffna():
    """daffna()"""
    return _cspice_swig.daffna()

def dafopr(CONST_STRING):
    """dafopr(char * CONST_STRING)"""
    return _cspice_swig.dafopr(CONST_STRING)

def dafus(sum, nd, ni):
    """dafus(double [128] sum, int nd, int ni)"""
    return _cspice_swig.dafus(sum, nd, ni)

def dcyldr(x, y, z):
    """dcyldr(double x, double y, double z)"""
    return _cspice_swig.dcyldr(x, y, z)

def deltet(epoch, CONST_STRING):
    """deltet(double epoch, char * CONST_STRING)"""
    return _cspice_swig.deltet(epoch, CONST_STRING)

def det(m1):
    """det(double [3][3] m1) -> double"""
    return _cspice_swig.det(m1)

def dgeodr(x, y, z, re, f):
    """dgeodr(double x, double y, double z, double re, double f)"""
    return _cspice_swig.dgeodr(x, y, z, re, f)

def diags2(symmat):
    """diags2(double [2][2] symmat)"""
    return _cspice_swig.diags2(symmat)

def dlatdr(x, y, z):
    """dlatdr(double x, double y, double z)"""
    return _cspice_swig.dlatdr(x, y, z)

def dpgrdr(CONST_STRING, x, y, z, re, f):
    """dpgrdr(char * CONST_STRING, double x, double y, double z, double re, double f)"""
    return _cspice_swig.dpgrdr(CONST_STRING, x, y, z, re, f)

def dpmax():
    """dpmax() -> double"""
    return _cspice_swig.dpmax()

def dpmin():
    """dpmin() -> double"""
    return _cspice_swig.dpmin()

def dpr():
    """dpr() -> double"""
    return _cspice_swig.dpr()

def drdcyl(r, lon, z):
    """drdcyl(double r, double lon, double z)"""
    return _cspice_swig.drdcyl(r, lon, z)

def drdgeo(lon, lat, alt, re, f):
    """drdgeo(double lon, double lat, double alt, double re, double f)"""
    return _cspice_swig.drdgeo(lon, lat, alt, re, f)

def drdlat(r, lon, lat):
    """drdlat(double r, double lon, double lat)"""
    return _cspice_swig.drdlat(r, lon, lat)

def drdpgr(CONST_STRING, lon, lat, alt, re, f):
    """drdpgr(char * CONST_STRING, double lon, double lat, double alt, double re, double f)"""
    return _cspice_swig.drdpgr(CONST_STRING, lon, lat, alt, re, f)

def drdsph(r, colat, lon):
    """drdsph(double r, double colat, double lon)"""
    return _cspice_swig.drdsph(r, colat, lon)

def dsphdr(x, y, z):
    """dsphdr(double x, double y, double z)"""
    return _cspice_swig.dsphdr(x, y, z)

def dtpool(CONST_STRING):
    """dtpool(char * CONST_STRING)"""
    return _cspice_swig.dtpool(CONST_STRING)

def ducrss(s1, s2):
    """ducrss(double [6] s1, double [6] s2)"""
    return _cspice_swig.ducrss(s1, s2)

def dvcrss(s1, s2):
    """dvcrss(double [6] s1, double [6] s2)"""
    return _cspice_swig.dvcrss(s1, s2)

def dvdot(s1, s2):
    """dvdot(double [6] s1, double [6] s2) -> double"""
    return _cspice_swig.dvdot(s1, s2)

def dvhat(s1):
    """dvhat(double [6] s1)"""
    return _cspice_swig.dvhat(s1)

def dvnorm(state):
    """dvnorm(double [6] state) -> double"""
    return _cspice_swig.dvnorm(state)

def dvpool(CONST_STRING):
    """dvpool(char * CONST_STRING)"""
    return _cspice_swig.dvpool(CONST_STRING)

def dvsep(s1, s2):
    """dvsep(double [6] s1, double [6] s2) -> double"""
    return _cspice_swig.dvsep(s1, s2)

def edlimb(a, b, c, viewpt):
    """edlimb(double a, double b, double c, double [3] viewpt)"""
    return _cspice_swig.edlimb(a, b, c, viewpt)

def edterm(trmtyp, source, target, et, fixref, abcorr, obsrvr, npts):
    """edterm(char * trmtyp, char * source, char * target, double et, char * fixref, char * abcorr, char * obsrvr, int npts)"""
    return _cspice_swig.edterm(trmtyp, source, target, et, fixref, abcorr, obsrvr, npts)

def el2cgv(ellipse):
    """el2cgv(double [NELLIPSE] ellipse)"""
    return _cspice_swig.el2cgv(ellipse)

def eqncpv(et, epoch, eqel, rapol, decpol):
    """eqncpv(double et, double epoch, double [9] eqel, double rapol, double decpol)"""
    return _cspice_swig.eqncpv(et, epoch, eqel, rapol, decpol)

def erract(CONST_STRING, lenout):
    """erract(char * CONST_STRING, int lenout)"""
    return _cspice_swig.erract(CONST_STRING, lenout)

def errch(arg1, arg2):
    """errch(char * arg1, char * arg2)"""
    return _cspice_swig.errch(arg1, arg2)

def errdev(CONST_STRING, lenout):
    """errdev(char * CONST_STRING, int lenout)"""
    return _cspice_swig.errdev(CONST_STRING, lenout)

def errdp(CONST_STRING, number):
    """errdp(char * CONST_STRING, double number)"""
    return _cspice_swig.errdp(CONST_STRING, number)

def errint(CONST_STRING, number):
    """errint(char * CONST_STRING, int number)"""
    return _cspice_swig.errint(CONST_STRING, number)

def errprt(CONST_STRING, lenout):
    """errprt(char * CONST_STRING, int lenout)"""
    return _cspice_swig.errprt(CONST_STRING, lenout)

def et2lst(et, body, lon, ltype):
    """et2lst(double et, int body, double lon, char * ltype)"""
    return _cspice_swig.et2lst(et, body, lon, ltype)

def et2utc(et, CONST_STRING, prec):
    """et2utc(double et, char * CONST_STRING, int prec)"""
    return _cspice_swig.et2utc(et, CONST_STRING, prec)

def etcal(et):
    """etcal(double et)"""
    return _cspice_swig.etcal(et)

def eul2m(angle3, angle2, angle1, axis3, axis2, axis1):
    """eul2m(double angle3, double angle2, double angle1, int axis3, int axis2, int axis1)"""
    return _cspice_swig.eul2m(angle3, angle2, angle1, axis3, axis2, axis1)

def eul2xf(eulang, axisa, axisb, axisc):
    """eul2xf(double [6] eulang, int axisa, int axisb, int axisc)"""
    return _cspice_swig.eul2xf(eulang, axisa, axisb, axisc)

def expool(CONST_STRING):
    """expool(char * CONST_STRING)"""
    return _cspice_swig.expool(CONST_STRING)

def failed():
    """failed() -> int"""
    return _cspice_swig.failed()

def fovray(inst, raydir, rframe, abcorr, observer, et, visible):
    """fovray(char * inst, double [3] raydir, char * rframe, char * abcorr, char * observer, double et, int * visible)"""
    return _cspice_swig.fovray(inst, raydir, rframe, abcorr, observer, et, visible)

def fovtrg(inst, target, tshape, tframe, abcorr, observer, et, visible):
    """fovtrg(char * inst, char * target, char * tshape, char * tframe, char * abcorr, char * observer, double et, int * visible)"""
    return _cspice_swig.fovtrg(inst, target, tshape, tframe, abcorr, observer, et, visible)

def frame(xin):
    """frame(double [3] xin)"""
    return _cspice_swig.frame(xin)

def frinfo(frcode):
    """frinfo(int frcode)"""
    return _cspice_swig.frinfo(frcode)

def frmchg(frame1, frame2, et):
    """frmchg(int frame1, int frame2, double et)"""
    return _cspice_swig.frmchg(frame1, frame2, et)

def frmchg_(frame1, frame2, et, xform):
    """frmchg_(int * frame1, int * frame2, double * et, double * xform)"""
    return _cspice_swig.frmchg_(frame1, frame2, et, xform)

def frmnam(frcode):
    """frmnam(int frcode)"""
    return _cspice_swig.frmnam(frcode)

def furnsh(CONST_STRING):
    """furnsh(char * CONST_STRING)"""
    return _cspice_swig.furnsh(CONST_STRING)

def gcpool(CONST_STRING, start):
    """gcpool(char * CONST_STRING, int start)"""
    return _cspice_swig.gcpool(CONST_STRING, start)

def gdpool(CONST_STRING, start):
    """gdpool(char * CONST_STRING, int start)"""
    return _cspice_swig.gdpool(CONST_STRING, start)

def georec(lon, lat, alt, re, f):
    """georec(double lon, double lat, double alt, double re, double f)"""
    return _cspice_swig.georec(lon, lat, alt, re, f)

def getfov(instid):
    """getfov(int instid)"""
    return _cspice_swig.getfov(instid)

def getmsg(CONST_STRING):
    """getmsg(char * CONST_STRING)"""
    return _cspice_swig.getmsg(CONST_STRING)

def gipool(CONST_STRING, start):
    """gipool(char * CONST_STRING, int start)"""
    return _cspice_swig.gipool(CONST_STRING, start)

def gnpool(CONST_STRING, start):
    """gnpool(char * CONST_STRING, int start)"""
    return _cspice_swig.gnpool(CONST_STRING, start)

def halfpi():
    """halfpi() -> double"""
    return _cspice_swig.halfpi()

def ident():
    """ident()"""
    return _cspice_swig.ident()

def illum(arg1, et, arg3, arg4, spoint):
    """illum(char * arg1, double et, char * arg3, char * arg4, double [3] spoint)"""
    return _cspice_swig.illum(arg1, et, arg3, arg4, spoint)

def illumf(arg1, arg2, arg3, et, arg5, arg6, arg7, spoint):
    """illumf(char * arg1, char * arg2, char * arg3, double et, char * arg5, char * arg6, char * arg7, double [3] spoint)"""
    return _cspice_swig.illumf(arg1, arg2, arg3, et, arg5, arg6, arg7, spoint)

def illumg(arg1, arg2, arg3, et, arg5, arg6, arg7, spoint):
    """illumg(char * arg1, char * arg2, char * arg3, double et, char * arg5, char * arg6, char * arg7, double [3] spoint)"""
    return _cspice_swig.illumg(arg1, arg2, arg3, et, arg5, arg6, arg7, spoint)

def ilumin(arg1, arg2, et, arg4, arg5, arg6, spoint):
    """ilumin(char * arg1, char * arg2, double et, char * arg4, char * arg5, char * arg6, double [3] spoint)"""
    return _cspice_swig.ilumin(arg1, arg2, et, arg4, arg5, arg6, spoint)

def inedpl(a, b, c, plane):
    """inedpl(double a, double b, double c, double [NPLANE] plane)"""
    return _cspice_swig.inedpl(a, b, c, plane)

def inelpl(ellipse, plane):
    """inelpl(double [NELLIPSE] ellipse, double [NPLANE] plane)"""
    return _cspice_swig.inelpl(ellipse, plane)

def inrypl(vertex, dir, plane):
    """inrypl(double [3] vertex, double [3] dir, double [NPLANE] plane)"""
    return _cspice_swig.inrypl(vertex, dir, plane)

def intmax():
    """intmax() -> int"""
    return _cspice_swig.intmax()

def intmin():
    """intmin() -> int"""
    return _cspice_swig.intmin()

def invert(m1):
    """invert(double [3][3] m1)"""
    return _cspice_swig.invert(m1)

def invort(m):
    """invort(double [3][3] m)"""
    return _cspice_swig.invort(m)

def isrot(m, ntol, dtol):
    """isrot(double [3][3] m, double ntol, double dtol) -> int"""
    return _cspice_swig.isrot(m, ntol, dtol)

def j1900():
    """j1900() -> double"""
    return _cspice_swig.j1900()

def j1950():
    """j1950() -> double"""
    return _cspice_swig.j1950()

def j2000():
    """j2000() -> double"""
    return _cspice_swig.j2000()

def j2100():
    """j2100() -> double"""
    return _cspice_swig.j2100()

def jyear():
    """jyear() -> double"""
    return _cspice_swig.jyear()

def latcyl(radius, lon, lat):
    """latcyl(double radius, double lon, double lat)"""
    return _cspice_swig.latcyl(radius, lon, lat)

def latrec(radius, longitude, latitude):
    """latrec(double radius, double longitude, double latitude)"""
    return _cspice_swig.latrec(radius, longitude, latitude)

def latsrf(method, target, et, fixref, lonlat, npts):
    """latsrf(char * method, char * target, double et, char * fixref, double * lonlat, int npts)"""
    return _cspice_swig.latsrf(method, target, et, fixref, lonlat, npts)

def latsph(radius, lon, lat):
    """latsph(double radius, double lon, double lat)"""
    return _cspice_swig.latsph(radius, lon, lat)

def ldpool(CONST_STRING):
    """ldpool(char * CONST_STRING)"""
    return _cspice_swig.ldpool(CONST_STRING)

def limbpt(method, target, et, fixref, abcorr, corloc, obsrvr, refvec, rolstp, ncuts, schstp, soltol, maxn):
    """limbpt(char * method, char * target, double et, char * fixref, char * abcorr, char * corloc, char * obsrvr, double [3] refvec, double rolstp, int ncuts, double schstp, double soltol, int maxn)"""
    return _cspice_swig.limbpt(method, target, et, fixref, abcorr, corloc, obsrvr, refvec, rolstp, ncuts, schstp, soltol, maxn)

def lspcn(arg1, et, arg3):
    """lspcn(char * arg1, double et, char * arg3) -> double"""
    return _cspice_swig.lspcn(arg1, et, arg3)

def ltime(etobs, obs, CONST_STRING, targ):
    """ltime(double etobs, int obs, char * CONST_STRING, int targ)"""
    return _cspice_swig.ltime(etobs, obs, CONST_STRING, targ)

def m2eul(rin, axis3, axis2, axis1):
    """m2eul(double [3][3] rin, int axis3, int axis2, int axis1)"""
    return _cspice_swig.m2eul(rin, axis3, axis2, axis1)

def m2q(rin):
    """m2q(double [3][3] rin)"""
    return _cspice_swig.m2q(rin)

def mequ(m1):
    """mequ(double [3][3] m1)"""
    return _cspice_swig.mequ(m1)

def mequg(m1, mout, nr_vout, nc_vout):
    """mequg(double * m1, double ** mout, int * nr_vout, int * nc_vout)"""
    return _cspice_swig.mequg(m1, mout, nr_vout, nc_vout)

def mtxm(m1, m2):
    """mtxm(double [3][3] m1, double [3][3] m2)"""
    return _cspice_swig.mtxm(m1, m2)

def mtxmg(m1, m2):
    """mtxmg(double * m1, double * m2)"""
    return _cspice_swig.mtxmg(m1, m2)

def mtxv(m1, vin):
    """mtxv(double [3][3] m1, double [3] vin)"""
    return _cspice_swig.mtxv(m1, vin)

def mtxvg(m1, v2):
    """mtxvg(double * m1, double * v2)"""
    return _cspice_swig.mtxvg(m1, v2)

def mxm(m1, m2):
    """mxm(double [3][3] m1, double [3][3] m2)"""
    return _cspice_swig.mxm(m1, m2)

def mxmg(m1, m2):
    """mxmg(double * m1, double * m2)"""
    return _cspice_swig.mxmg(m1, m2)

def mxmt(m1, m2):
    """mxmt(double [3][3] m1, double [3][3] m2)"""
    return _cspice_swig.mxmt(m1, m2)

def mxmtg(m1, m2):
    """mxmtg(double * m1, double * m2)"""
    return _cspice_swig.mxmtg(m1, m2)

def mxv(m1, vin):
    """mxv(double [3][3] m1, double [3] vin)"""
    return _cspice_swig.mxv(m1, vin)

def mxvg(m1, v2):
    """mxvg(double * m1, double * v2)"""
    return _cspice_swig.mxvg(m1, v2)

def namfrm(CONST_STRING):
    """namfrm(char * CONST_STRING)"""
    return _cspice_swig.namfrm(CONST_STRING)

def nearpt(positn, a, b, c):
    """nearpt(double [3] positn, double a, double b, double c)"""
    return _cspice_swig.nearpt(positn, a, b, c)

def npedln(a, b, c, linept, linedr):
    """npedln(double a, double b, double c, double [3] linept, double [3] linedr)"""
    return _cspice_swig.npedln(a, b, c, linept, linedr)

def npelpt(point):
    """npelpt(double [3] point)"""
    return _cspice_swig.npelpt(point)

def nplnpt(linpt, lindir, point):
    """nplnpt(double [3] linpt, double [3] lindir, double [3] point)"""
    return _cspice_swig.nplnpt(linpt, lindir, point)

def nvc2pl(normal, constant):
    """nvc2pl(double [3] normal, double constant)"""
    return _cspice_swig.nvc2pl(normal, constant)

def nvp2pl(normal, point):
    """nvp2pl(double [3] normal, double [3] point)"""
    return _cspice_swig.nvp2pl(normal, point)

def occult(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, et):
    """occult(char * arg1, char * arg2, char * arg3, char * arg4, char * arg5, char * arg6, char * arg7, char * arg8, double et)"""
    return _cspice_swig.occult(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, et)

def oscelt(state, et, mu):
    """oscelt(double [6] state, double et, double mu)"""
    return _cspice_swig.oscelt(state, et, mu)

def oscltx(state, et, mu):
    """oscltx(double [6] state, double et, double mu)"""
    return _cspice_swig.oscltx(state, et, mu)

def pckcov(pck, idcode):
    """pckcov(char * pck, int idcode)"""
    return _cspice_swig.pckcov(pck, idcode)

def pcpool(CONST_STRING, n):
    """pcpool(char * CONST_STRING, int n)"""
    return _cspice_swig.pcpool(CONST_STRING, n)

def pdpool(CONST_STRING, n):
    """pdpool(char * CONST_STRING, int n)"""
    return _cspice_swig.pdpool(CONST_STRING, n)

def pgrrec(CONST_STRING, lon, lat, alt, re, f):
    """pgrrec(char * CONST_STRING, double lon, double lat, double alt, double re, double f)"""
    return _cspice_swig.pgrrec(CONST_STRING, lon, lat, alt, re, f)

def phaseq(et, arg2, arg3, arg4, arg5):
    """phaseq(double et, char * arg2, char * arg3, char * arg4, char * arg5) -> double"""
    return _cspice_swig.phaseq(et, arg2, arg3, arg4, arg5)

def pi():
    """pi() -> double"""
    return _cspice_swig.pi()

def pipool(CONST_STRING, n):
    """pipool(char * CONST_STRING, int n)"""
    return _cspice_swig.pipool(CONST_STRING, n)

def pjelpl(elin, plane):
    """pjelpl(double [NELLIPSE] elin, double [NPLANE] plane)"""
    return _cspice_swig.pjelpl(elin, plane)

def pltar(nv, np):
    """pltar(int nv, int np) -> double"""
    return _cspice_swig.pltar(nv, np)

def pltexp(iverts, delta):
    """pltexp(double [3][3] iverts, double delta)"""
    return _cspice_swig.pltexp(iverts, delta)

def pltnp(point, v1, v2, v3):
    """pltnp(double [3] point, double [3] v1, double [3] v2, double [3] v3)"""
    return _cspice_swig.pltnp(point, v1, v2, v3)

def pltvol(nv, np):
    """pltvol(int nv, int np) -> double"""
    return _cspice_swig.pltvol(nv, np)

def pl2nvc(plane, normal):
    """pl2nvc(double [NPLANE] plane, double [3] normal)"""
    return _cspice_swig.pl2nvc(plane, normal)

def pl2nvp(plane):
    """pl2nvp(double [NPLANE] plane)"""
    return _cspice_swig.pl2nvp(plane)

def pl2psv(plane):
    """pl2psv(double [NPLANE] plane)"""
    return _cspice_swig.pl2psv(plane)

def prop2b(gm, pvinit, dt):
    """prop2b(double gm, double [6] pvinit, double dt)"""
    return _cspice_swig.prop2b(gm, pvinit, dt)

def psv2pl(point, span1, span2):
    """psv2pl(double [3] point, double [3] span1, double [3] span2)"""
    return _cspice_swig.psv2pl(point, span1, span2)

def pxform(arg1, arg2, et):
    """pxform(char * arg1, char * arg2, double et)"""
    return _cspice_swig.pxform(arg1, arg2, et)

def pxfrm2(arg1, arg2, etfrom, et2):
    """pxfrm2(char * arg1, char * arg2, double etfrom, double et2)"""
    return _cspice_swig.pxfrm2(arg1, arg2, etfrom, et2)

def q2m(qin):
    """q2m(double [4] qin)"""
    return _cspice_swig.q2m(qin)

def qdq2av(qin, dq):
    """qdq2av(double [4] qin, double [4] dq)"""
    return _cspice_swig.qdq2av(qin, dq)

def qxq(q1, q2):
    """qxq(double [4] q1, double [4] q2)"""
    return _cspice_swig.qxq(q1, q2)

def radrec(range, ra, dec):
    """radrec(double range, double ra, double dec)"""
    return _cspice_swig.radrec(range, ra, dec)

def rav2xf(rot, av):
    """rav2xf(double [3][3] rot, double [3] av)"""
    return _cspice_swig.rav2xf(rot, av)

def raxisa(matrix):
    """raxisa(double [3][3] matrix)"""
    return _cspice_swig.raxisa(matrix)

def reccyl(rectan1):
    """reccyl(double [3] rectan1)"""
    return _cspice_swig.reccyl(rectan1)

def recgeo(rectan1, re, f):
    """recgeo(double [3] rectan1, double re, double f)"""
    return _cspice_swig.recgeo(rectan1, re, f)

def reclat(rectan1):
    """reclat(double [3] rectan1)"""
    return _cspice_swig.reclat(rectan1)

def recpgr(CONST_STRING, rectan1, re, f):
    """recpgr(char * CONST_STRING, double [3] rectan1, double re, double f)"""
    return _cspice_swig.recpgr(CONST_STRING, rectan1, re, f)

def recrad(rectan):
    """recrad(double [3] rectan)"""
    return _cspice_swig.recrad(rectan)

def recsph(rectan):
    """recsph(double [3] rectan)"""
    return _cspice_swig.recsph(rectan)

def refchg(frame1, frame2, et):
    """refchg(int frame1, int frame2, double et)"""
    return _cspice_swig.refchg(frame1, frame2, et)

def refchg_(frame1, frame2, et, rotate):
    """refchg_(int * frame1, int * frame2, double * et, double * rotate)"""
    return _cspice_swig.refchg_(frame1, frame2, et, rotate)

def repmc(arg1, arg2, arg3):
    """repmc(char * arg1, char * arg2, char * arg3)"""
    return _cspice_swig.repmc(arg1, arg2, arg3)

def repmct(arg1, arg2, value, IN_STRING):
    """repmct(char * arg1, char * arg2, int value, char IN_STRING)"""
    return _cspice_swig.repmct(arg1, arg2, value, IN_STRING)

def repmd(arg1, arg2, value, sigdig):
    """repmd(char * arg1, char * arg2, double value, int sigdig)"""
    return _cspice_swig.repmd(arg1, arg2, value, sigdig)

def repmf(arg1, arg2, value, sigdig, format):
    """repmf(char * arg1, char * arg2, double value, int sigdig, char format)"""
    return _cspice_swig.repmf(arg1, arg2, value, sigdig, format)

def repmi(arg1, arg2, value, lenout, out):
    """repmi(char * arg1, char * arg2, int value, int lenout, char * out)"""
    return _cspice_swig.repmi(arg1, arg2, value, lenout, out)

def repmot(arg1, arg2, value, IN_STRING):
    """repmot(char * arg1, char * arg2, int value, char IN_STRING)"""
    return _cspice_swig.repmot(arg1, arg2, value, IN_STRING)

def reset():
    """reset()"""
    return _cspice_swig.reset()

def rotate(angle, iaxis):
    """rotate(double angle, int iaxis)"""
    return _cspice_swig.rotate(angle, iaxis)

def rotmat(m1, angle, iaxis):
    """rotmat(double [3][3] m1, double angle, int iaxis)"""
    return _cspice_swig.rotmat(m1, angle, iaxis)

def rotvec(v1, angle, iaxis):
    """rotvec(double [3] v1, double angle, int iaxis)"""
    return _cspice_swig.rotvec(v1, angle, iaxis)

def rpd():
    """rpd() -> double"""
    return _cspice_swig.rpd()

def rquad(a, b, c):
    """rquad(double a, double b, double c)"""
    return _cspice_swig.rquad(a, b, c)

def saelgv(vec1, vec2):
    """saelgv(double [3] vec1, double [3] vec2)"""
    return _cspice_swig.saelgv(vec1, vec2)

def scdecd(sc, sclkdp):
    """scdecd(int sc, double sclkdp)"""
    return _cspice_swig.scdecd(sc, sclkdp)

def sce2c(sc, et):
    """sce2c(int sc, double et)"""
    return _cspice_swig.sce2c(sc, et)

def sce2s(sc, et):
    """sce2s(int sc, double et)"""
    return _cspice_swig.sce2s(sc, et)

def sce2t(sc, et):
    """sce2t(int sc, double et)"""
    return _cspice_swig.sce2t(sc, et)

def scencd(sc, CONST_STRING):
    """scencd(int sc, char * CONST_STRING)"""
    return _cspice_swig.scencd(sc, CONST_STRING)

def scfmt(sc, ticks):
    """scfmt(int sc, double ticks)"""
    return _cspice_swig.scfmt(sc, ticks)

def scpart(sc):
    """scpart(int sc)"""
    return _cspice_swig.scpart(sc)

def scs2e(sc, CONST_STRING):
    """scs2e(int sc, char * CONST_STRING)"""
    return _cspice_swig.scs2e(sc, CONST_STRING)

def sct2e(sc, sclkdp):
    """sct2e(int sc, double sclkdp)"""
    return _cspice_swig.sct2e(sc, sclkdp)

def sctiks(sc, CONST_STRING):
    """sctiks(int sc, char * CONST_STRING)"""
    return _cspice_swig.sctiks(sc, CONST_STRING)

def setmsg(CONST_STRING):
    """setmsg(char * CONST_STRING)"""
    return _cspice_swig.setmsg(CONST_STRING)

def sigerr(CONST_STRING):
    """sigerr(char * CONST_STRING)"""
    return _cspice_swig.sigerr(CONST_STRING)

def sincpt(arg1, arg2, et, arg4, arg5, arg6, arg7, dvec):
    """sincpt(char * arg1, char * arg2, double et, char * arg4, char * arg5, char * arg6, char * arg7, double [3] dvec)"""
    return _cspice_swig.sincpt(arg1, arg2, et, arg4, arg5, arg6, arg7, dvec)

def spd():
    """spd() -> double"""
    return _cspice_swig.spd()

def sphcyl(radius, colat, slon):
    """sphcyl(double radius, double colat, double slon)"""
    return _cspice_swig.sphcyl(radius, colat, slon)

def sphlat(r, colat, lons):
    """sphlat(double r, double colat, double lons)"""
    return _cspice_swig.sphlat(r, colat, lons)

def sphrec(r, colat, lon):
    """sphrec(double r, double colat, double lon)"""
    return _cspice_swig.sphrec(r, colat, lon)

def spkacs(targ, et, arg3, arg4, obs, starg):
    """spkacs(int targ, double et, char * arg3, char * arg4, int obs, double * starg)"""
    return _cspice_swig.spkacs(targ, et, arg3, arg4, obs, starg)

def spkapo(targ, et, arg3, sobs, arg5):
    """spkapo(int targ, double et, char * arg3, double [6] sobs, char * arg5)"""
    return _cspice_swig.spkapo(targ, et, arg3, sobs, arg5)

def spkapp(targ, et, arg3, sobs, arg5):
    """spkapp(int targ, double et, char * arg3, double [6] sobs, char * arg5)"""
    return _cspice_swig.spkapp(targ, et, arg3, sobs, arg5)

def spkaps(targ, et, arg3, arg4, stobs, accobs):
    """spkaps(int targ, double et, char * arg3, char * arg4, double [6] stobs, double [6] accobs)"""
    return _cspice_swig.spkaps(targ, et, arg3, arg4, stobs, accobs)

def spkcov(spk, idcode):
    """spkcov(char * spk, int idcode)"""
    return _cspice_swig.spkcov(spk, idcode)

def spkez(targ, et, arg3, arg4, obs):
    """spkez(int targ, double et, char * arg3, char * arg4, int obs)"""
    return _cspice_swig.spkez(targ, et, arg3, arg4, obs)

def spkez_vector(targ, et, ref, abcorr, obs):
    """spkez_vector(int targ, double * et, char * ref, char * abcorr, int obs)"""
    return _cspice_swig.spkez_vector(targ, et, ref, abcorr, obs)

def spkezp(targ, et, arg3, arg4, obs):
    """spkezp(int targ, double et, char * arg3, char * arg4, int obs)"""
    return _cspice_swig.spkezp(targ, et, arg3, arg4, obs)

def spkezr(arg1, et, arg3, arg4, arg5):
    """spkezr(char * arg1, double et, char * arg3, char * arg4, char * arg5)"""
    return _cspice_swig.spkezr(arg1, et, arg3, arg4, arg5)

def spkgeo(targ, et, CONST_STRING, obs):
    """spkgeo(int targ, double et, char * CONST_STRING, int obs)"""
    return _cspice_swig.spkgeo(targ, et, CONST_STRING, obs)

def spkgps(targ, et, CONST_STRING, obs):
    """spkgps(int targ, double et, char * CONST_STRING, int obs)"""
    return _cspice_swig.spkgps(targ, et, CONST_STRING, obs)

def spkltc(targ, et, arg3, arg4, stobs, starg):
    """spkltc(int targ, double et, char * arg3, char * arg4, double [6] stobs, double [6] starg)"""
    return _cspice_swig.spkltc(targ, et, arg3, arg4, stobs, starg)

def spkobj(spk):
    """spkobj(char * spk)"""
    return _cspice_swig.spkobj(spk)

def spkpos(arg1, et, arg3, arg4, arg5):
    """spkpos(char * arg1, double et, char * arg3, char * arg4, char * arg5)"""
    return _cspice_swig.spkpos(arg1, et, arg3, arg4, arg5)

def spkssb(targ, et, CONST_STRING):
    """spkssb(int targ, double et, char * CONST_STRING)"""
    return _cspice_swig.spkssb(targ, et, CONST_STRING)

def srfc2s(code, bodyid):
    """srfc2s(int code, int bodyid)"""
    return _cspice_swig.srfc2s(code, bodyid)

def srfcss(code, CONST_STRING):
    """srfcss(int code, char * CONST_STRING)"""
    return _cspice_swig.srfcss(code, CONST_STRING)

def srfnrm(method, target, et, fixref, npts):
    """srfnrm(char * method, char * target, double et, char * fixref, int npts)"""
    return _cspice_swig.srfnrm(method, target, et, fixref, npts)

def srfrec(body, longitude, latitude):
    """srfrec(int body, double longitude, double latitude)"""
    return _cspice_swig.srfrec(body, longitude, latitude)

def srfs2c(arg1, arg2):
    """srfs2c(char * arg1, char * arg2)"""
    return _cspice_swig.srfs2c(arg1, arg2)

def srfscc(CONST_STRING, body_id):
    """srfscc(char * CONST_STRING, int body_id)"""
    return _cspice_swig.srfscc(CONST_STRING, body_id)

def srfxpt(arg1, arg2, et, arg4, arg5, arg6, dvec):
    """srfxpt(char * arg1, char * arg2, double et, char * arg4, char * arg5, char * arg6, double [3] dvec)"""
    return _cspice_swig.srfxpt(arg1, arg2, et, arg4, arg5, arg6, dvec)

def stcf01(catnam, westra, eastra, sthdec, nthdec):
    """stcf01(char * catnam, double westra, double eastra, double sthdec, double nthdec)"""
    return _cspice_swig.stcf01(catnam, westra, eastra, sthdec, nthdec)

def stcg01(index):
    """stcg01(int index)"""
    return _cspice_swig.stcg01(index)

def stcl01(catfnm):
    """stcl01(char * catfnm)"""
    return _cspice_swig.stcl01(catfnm)

def stelab(pobj, vobs):
    """stelab(double [3] pobj, double [3] vobs)"""
    return _cspice_swig.stelab(pobj, vobs)

def stlabx(pobj, vobs):
    """stlabx(double [3] pobj, double [3] vobs)"""
    return _cspice_swig.stlabx(pobj, vobs)

def stpool(arg1, nth, arg3):
    """stpool(char * arg1, int nth, char * arg3)"""
    return _cspice_swig.stpool(arg1, nth, arg3)

def str2et(CONST_STRING):
    """str2et(char * CONST_STRING)"""
    return _cspice_swig.str2et(CONST_STRING)

def subpnt(arg1, arg2, et, arg4, arg5, arg6):
    """subpnt(char * arg1, char * arg2, double et, char * arg4, char * arg5, char * arg6)"""
    return _cspice_swig.subpnt(arg1, arg2, et, arg4, arg5, arg6)

def subpt(arg1, arg2, et, arg4, arg5):
    """subpt(char * arg1, char * arg2, double et, char * arg4, char * arg5)"""
    return _cspice_swig.subpt(arg1, arg2, et, arg4, arg5)

def subslr(arg1, arg2, et, arg4, arg5, arg6):
    """subslr(char * arg1, char * arg2, double et, char * arg4, char * arg5, char * arg6)"""
    return _cspice_swig.subslr(arg1, arg2, et, arg4, arg5, arg6)

def subsol(arg1, arg2, et, arg4, arg5):
    """subsol(char * arg1, char * arg2, double et, char * arg4, char * arg5)"""
    return _cspice_swig.subsol(arg1, arg2, et, arg4, arg5)

def surfnm(a, b, c, point):
    """surfnm(double a, double b, double c, double [3] point)"""
    return _cspice_swig.surfnm(a, b, c, point)

def surfpt(positn, u, a, b, c):
    """surfpt(double [3] positn, double [3] u, double a, double b, double c)"""
    return _cspice_swig.surfpt(positn, u, a, b, c)

def surfpv(stvrtx, stdir, a, b, c):
    """surfpv(double [6] stvrtx, double [6] stdir, double a, double b, double c)"""
    return _cspice_swig.surfpv(stvrtx, stdir, a, b, c)

def sxform(arg1, arg2, et):
    """sxform(char * arg1, char * arg2, double et)"""
    return _cspice_swig.sxform(arg1, arg2, et)

def sxform_vector(_from, to, et):
    """sxform_vector(char * _from, char * to, double * et)"""
    return _cspice_swig.sxform_vector(_from, to, et)

def timdef(arg1, arg2):
    """timdef(char * arg1, char * arg2)"""
    return _cspice_swig.timdef(arg1, arg2)

def timout(et, CONST_STRING):
    """timout(double et, char * CONST_STRING)"""
    return _cspice_swig.timout(et, CONST_STRING)

def tipbod(CONST_STRING, body, et):
    """tipbod(char * CONST_STRING, int body, double et)"""
    return _cspice_swig.tipbod(CONST_STRING, body, et)

def tisbod(CONST_STRING, body, et):
    """tisbod(char * CONST_STRING, int body, double et)"""
    return _cspice_swig.tisbod(CONST_STRING, body, et)

def tkvrsn(CONST_STRING):
    """tkvrsn(char * CONST_STRING) -> char *"""
    return _cspice_swig.tkvrsn(CONST_STRING)

def tparse(string):
    """tparse(char * string)"""
    return _cspice_swig.tparse(string)

def tpictr(sample):
    """tpictr(char * sample)"""
    return _cspice_swig.tpictr(sample)

def trace(matrix):
    """trace(double [3][3] matrix) -> double"""
    return _cspice_swig.trace(matrix)

def trcoff():
    """trcoff()"""
    return _cspice_swig.trcoff()

def trcdep():
    """trcdep()"""
    return _cspice_swig.trcdep()

def tsetyr(year):
    """tsetyr(int year)"""
    return _cspice_swig.tsetyr(year)

def twopi():
    """twopi() -> double"""
    return _cspice_swig.twopi()

def twovec(axdef, indexa, plndef, indexp):
    """twovec(double [3] axdef, int indexa, double [3] plndef, int indexp)"""
    return _cspice_swig.twovec(axdef, indexa, plndef, indexp)

def tyear():
    """tyear() -> double"""
    return _cspice_swig.tyear()

def ucrss(v1, v2):
    """ucrss(double [3] v1, double [3] v2)"""
    return _cspice_swig.ucrss(v1, v2)

def unitim(epoch, arg2, arg3):
    """unitim(double epoch, char * arg2, char * arg3) -> double"""
    return _cspice_swig.unitim(epoch, arg2, arg3)

def unload(CONST_STRING):
    """unload(char * CONST_STRING)"""
    return _cspice_swig.unload(CONST_STRING)

def unorm(v1):
    """unorm(double [3] v1)"""
    return _cspice_swig.unorm(v1)

def unormg(v1):
    """unormg(double * v1)"""
    return _cspice_swig.unormg(v1)

def utc2et(CONST_STRING):
    """utc2et(char const * CONST_STRING)"""
    return _cspice_swig.utc2et(CONST_STRING)

def vadd(v1, v2):
    """vadd(double [3] v1, double [3] v2)"""
    return _cspice_swig.vadd(v1, v2)

def vaddg(v1, v2):
    """vaddg(double * v1, double * v2)"""
    return _cspice_swig.vaddg(v1, v2)

def vcrss(v1, v2):
    """vcrss(double [3] v1, double [3] v2)"""
    return _cspice_swig.vcrss(v1, v2)

def vdist(v1, v2):
    """vdist(double [3] v1, double [3] v2) -> double"""
    return _cspice_swig.vdist(v1, v2)

def vdistg(v1, v2):
    """vdistg(double * v1, double * v2) -> double"""
    return _cspice_swig.vdistg(v1, v2)

def vdot(v1, v2):
    """vdot(double [3] v1, double [3] v2) -> double"""
    return _cspice_swig.vdot(v1, v2)

def vdotg(v1, v2):
    """vdotg(double * v1, double * v2) -> double"""
    return _cspice_swig.vdotg(v1, v2)

def vequ(vin):
    """vequ(double [3] vin)"""
    return _cspice_swig.vequ(vin)

def vequg(v1):
    """vequg(double * v1)"""
    return _cspice_swig.vequg(v1)

def vhat(v1):
    """vhat(double [3] v1)"""
    return _cspice_swig.vhat(v1)

def vhatg(v1):
    """vhatg(double * v1)"""
    return _cspice_swig.vhatg(v1)

def vlcom3(a, v1, b, v2, c, v3):
    """vlcom3(double a, double [3] v1, double b, double [3] v2, double c, double [3] v3)"""
    return _cspice_swig.vlcom3(a, v1, b, v2, c, v3)

def vlcom(a, v1, b, v2):
    """vlcom(double a, double [3] v1, double b, double [3] v2)"""
    return _cspice_swig.vlcom(a, v1, b, v2)

def vlcomg(a, v1, b, v2):
    """vlcomg(double a, double * v1, double b, double * v2)"""
    return _cspice_swig.vlcomg(a, v1, b, v2)

def vminug(v1):
    """vminug(double * v1)"""
    return _cspice_swig.vminug(v1)

def vminus(v1):
    """vminus(double [3] v1)"""
    return _cspice_swig.vminus(v1)

def vnorm(v1):
    """vnorm(double [3] v1) -> double"""
    return _cspice_swig.vnorm(v1)

def vnormg(v1):
    """vnormg(double * v1) -> double"""
    return _cspice_swig.vnormg(v1)

def vpack(x, y, z):
    """vpack(double x, double y, double z)"""
    return _cspice_swig.vpack(x, y, z)

def vperp(a, b):
    """vperp(double [3] a, double [3] b)"""
    return _cspice_swig.vperp(a, b)

def vprjp(vin, plane):
    """vprjp(double [3] vin, double [NPLANE] plane)"""
    return _cspice_swig.vprjp(vin, plane)

def vprjpi(vin, projpl, invpl):
    """vprjpi(double [3] vin, double [NPLANE] projpl, double [NPLANE] invpl)"""
    return _cspice_swig.vprjpi(vin, projpl, invpl)

def vproj(a, b):
    """vproj(double [3] a, double [3] b)"""
    return _cspice_swig.vproj(a, b)

def vrel(v1, v2):
    """vrel(double [3] v1, double [3] v2) -> double"""
    return _cspice_swig.vrel(v1, v2)

def vrelg(v1, v2):
    """vrelg(double * v1, double * v2) -> double"""
    return _cspice_swig.vrelg(v1, v2)

def vrotv(v, axis, theta):
    """vrotv(double [3] v, double [3] axis, double theta)"""
    return _cspice_swig.vrotv(v, axis, theta)

def vscl(s, v1):
    """vscl(double s, double [3] v1)"""
    return _cspice_swig.vscl(s, v1)

def vsclg(s, v1):
    """vsclg(double s, double * v1)"""
    return _cspice_swig.vsclg(s, v1)

def vsep(v1, v2):
    """vsep(double [3] v1, double [3] v2) -> double"""
    return _cspice_swig.vsep(v1, v2)

def vsepg(v1, v2):
    """vsepg(double * v1, double * v2) -> double"""
    return _cspice_swig.vsepg(v1, v2)

def vsub(v1, v2):
    """vsub(double [3] v1, double [3] v2)"""
    return _cspice_swig.vsub(v1, v2)

def vsubg(v1, v2):
    """vsubg(double * v1, double * v2)"""
    return _cspice_swig.vsubg(v1, v2)

def vtmv(v1, matrix):
    """vtmv(double [3] v1, double [3][3] matrix) -> double"""
    return _cspice_swig.vtmv(v1, matrix)

def vtmvg(v1, matrix, v2):
    """vtmvg(double * v1, double * matrix, double * v2) -> double"""
    return _cspice_swig.vtmvg(v1, matrix, v2)

def vupack(v):
    """vupack(double [3] v)"""
    return _cspice_swig.vupack(v)

def vzero(v):
    """vzero(double [3] v) -> int"""
    return _cspice_swig.vzero(v)

def vzerog(v):
    """vzerog(double * v) -> int"""
    return _cspice_swig.vzerog(v)

def xf2eul(xform, axisa, axisb, axisc):
    """xf2eul(double [6][6] xform, int axisa, int axisb, int axisc)"""
    return _cspice_swig.xf2eul(xform, axisa, axisb, axisc)

def xf2rav(xform):
    """xf2rav(double [6][6] xform)"""
    return _cspice_swig.xf2rav(xform)

def xpose6(m1):
    """xpose6(double [6][6] m1)"""
    return _cspice_swig.xpose6(m1)

def xpose(m1):
    """xpose(double [3][3] m1)"""
    return _cspice_swig.xpose(m1)

def xposeg(matrix):
    """xposeg(double * matrix)"""
    return _cspice_swig.xposeg(matrix)
# This file is compatible with both classic and new-style classes.


